# coding: utf-8

"""
    Хранение книг

    API для хранения книг  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_books_book_id_delete(self):
        """Test case for books_book_id_delete

        Удалить книгу  # noqa: E501
        """
        pass

    def test_books_book_id_get(self):
        """Test case for books_book_id_get

        Получить информацию о книге  # noqa: E501
        """
        pass

    def test_books_book_id_put(self):
        """Test case for books_book_id_put

        Обновить информацию о книге  # noqa: E501
        """
        pass

    def test_books_get(self):
        """Test case for books_get

        Получить список книг  # noqa: E501
        """
        pass

    def test_books_post(self):
        """Test case for books_post

        Добавить новую книгу  # noqa: E501
        """
        pass

    def test_books_search_get(self):
        """Test case for books_search_get

        Поиск книг по различным критериям  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
