name: startup application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  run-server:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: install server dependencies
      run: |
        cd server
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install prometheus_client
        pip install prometheus_flask_exporter
        
    - name: run Swagger
      run: |
        cd server
        python -m swagger_server.__main__ &
        
